#include <iostream>
bool MainWindow::onAddTab(QKeyEvent *keyEvent) {
    std::cout << "handle onAddTab" << std::flush;
    return false;
}

bool MainWindow::onBranchViewWithSubdirs(QKeyEvent *keyEvent) {
    std::cout << "handle onBranchViewWithSubdirs" << std::flush;
    return false;
}

bool MainWindow::onCDTree(QKeyEvent *keyEvent) {
    std::cout << "handle onCDTree" << std::flush;
    return false;
}

bool MainWindow::onCompareDirectories(QKeyEvent *keyEvent) {
    std::cout << "handle onCompareDirectories" << std::flush;
    return false;
}

bool MainWindow::onCopy(QKeyEvent *keyEvent) {
    std::cout << "handle onCopy" << std::flush;
    return false;
}

bool MainWindow::onCopyInPlace(QKeyEvent *keyEvent) {
    std::cout << "handle onCopyInPlace" << std::flush;
    return false;
}

bool MainWindow::onCurrentDirToCommandLine(QKeyEvent *keyEvent) {
    std::cout << "handle onCurrentDirToCommandLine" << std::flush;
    return false;
}

bool MainWindow::onCurrentNameToCommandLine(QKeyEvent *keyEvent) {
    std::cout << "handle onCurrentNameToCommandLine" << std::flush;
    return false;
}

bool MainWindow::onCurrentPathToCommandLine(QKeyEvent *keyEvent) {
    std::cout << "handle onCurrentPathToCommandLine" << std::flush;
    return false;
}

bool MainWindow::onDeletePermanently(QKeyEvent *keyEvent) {
    std::cout << "handle onDeletePermanently" << std::flush;
    return false;
}

bool MainWindow::onDeleteToTrash(QKeyEvent *keyEvent) {
    std::cout << "handle onDeleteToTrash" << std::flush;
    return false;
}

bool MainWindow::onDirHotlist(QKeyEvent *keyEvent) {
    std::cout << "handle onDirHotlist" << std::flush;
    return false;
}

bool MainWindow::onDirHotlistConfig(QKeyEvent *keyEvent) {
    std::cout << "handle onDirHotlistConfig" << std::flush;
    return false;
}

bool MainWindow::onEdit(QKeyEvent *keyEvent) {
    std::cout << "handle onEdit" << std::flush;
    return false;
}

bool MainWindow::onEditNew(QKeyEvent *keyEvent) {
    std::cout << "handle onEditNew" << std::flush;
    return false;
}

bool MainWindow::onExtractFiles(QKeyEvent *keyEvent) {
    std::cout << "handle onExtractFiles" << std::flush;
    return false;
}

bool MainWindow::onFileProperties(QKeyEvent *keyEvent) {
    std::cout << "handle onFileProperties" << std::flush;
    return false;
}

bool MainWindow::onFocusCommandLine(QKeyEvent *keyEvent) {
    std::cout << "handle onFocusCommandLine" << std::flush;
    return false;
}

bool MainWindow::onGoBack(QKeyEvent *keyEvent) {
    std::cout << "handle onGoBack" << std::flush;
    return false;
}

bool MainWindow::onGoForward(QKeyEvent *keyEvent) {
    std::cout << "handle onGoForward" << std::flush;
    return false;
}

bool MainWindow::onGoToFirstRow(QKeyEvent *keyEvent) {
    std::cout << "handle onGoToFirstRow" << std::flush;
    return false;
}

bool MainWindow::onGoToLastRow(QKeyEvent *keyEvent) {
    std::cout << "handle onGoToLastRow" << std::flush;
    return false;
}

bool MainWindow::onGoToNextTab(QKeyEvent *keyEvent) {
    std::cout << "handle onGoToNextTab" << std::flush;
    return false;
}

bool MainWindow::onGoToPreviousTab(QKeyEvent *keyEvent) {
    std::cout << "handle onGoToPreviousTab" << std::flush;
    return false;
}

bool MainWindow::onGoUpDir(QKeyEvent *keyEvent) {
    std::cout << "handle onGoUpDir" << std::flush;
    return false;
}

bool MainWindow::onInvertSelection(QKeyEvent *keyEvent) {
    std::cout << "handle onInvertSelection" << std::flush;
    return false;
}

bool MainWindow::onJumpDownToFiles(QKeyEvent *keyEvent) {
    std::cout << "handle onJumpDownToFiles" << std::flush;
    return false;
}

bool MainWindow::onJumpUpToDirectories(QKeyEvent *keyEvent) {
    std::cout << "handle onJumpUpToDirectories" << std::flush;
    return false;
}

bool MainWindow::onLocalSearch(QKeyEvent *keyEvent) {
    std::cout << "handle onLocalSearch" << std::flush;
    return false;
}

bool MainWindow::onMakeDirectory(QKeyEvent *keyEvent) {
    std::cout << "handle onMakeDirectory" << std::flush;
    return false;
}

bool MainWindow::onMakeDirectoryOpposite(QKeyEvent *keyEvent) {
    std::cout << "handle onMakeDirectoryOpposite" << std::flush;
    return false;
}

bool MainWindow::onMove(QKeyEvent *keyEvent) {
    std::cout << "handle onMove" << std::flush;
    return false;
}

bool MainWindow::onNextMatch(QKeyEvent *keyEvent) {
    std::cout << "handle onNextMatch" << std::flush;
    return false;
}

bool MainWindow::onOccupiedSpace(QKeyEvent *keyEvent) {
    std::cout << "handle onOccupiedSpace" << std::flush;
    return false;
}

bool MainWindow::onPackFiles(QKeyEvent *keyEvent) {
    std::cout << "handle onPackFiles" << std::flush;
    return false;
}

bool MainWindow::onPrevMatch(QKeyEvent *keyEvent) {
    std::cout << "handle onPrevMatch" << std::flush;
    return false;
}

bool MainWindow::onQuickView(QKeyEvent *keyEvent) {
    std::cout << "handle onQuickView" << std::flush;
    return false;
}

bool MainWindow::onRemoveTab(QKeyEvent *keyEvent) {
    std::cout << "handle onRemoveTab" << std::flush;
    return false;
}

bool MainWindow::onRename(QKeyEvent *keyEvent) {
    std::cout << "handle onRename" << std::flush;
    return false;
}

bool MainWindow::onRestoreSelection(QKeyEvent *keyEvent) {
    std::cout << "handle onRestoreSelection" << std::flush;
    return false;
}

bool MainWindow::onReturnToPanel(QKeyEvent *keyEvent) {
    std::cout << "handle onReturnToPanel" << std::flush;
    return false;
}

bool MainWindow::onSearchGlobal(QKeyEvent *keyEvent) {
    std::cout << "handle onSearchGlobal" << std::flush;
    return false;
}

bool MainWindow::onSelectAll(QKeyEvent *keyEvent) {
    std::cout << "handle onSelectAll" << std::flush;
    return false;
}

bool MainWindow::onSelectAllFromNumPlus(QKeyEvent *keyEvent) {
    std::cout << "handle onSelectAllFromNumPlus" << std::flush;
    return false;
}

bool MainWindow::onSelectGroup(QKeyEvent *keyEvent) {
    std::cout << "handle onSelectGroup" << std::flush;
    return false;
}

bool MainWindow::onSelectSameExtension(QKeyEvent *keyEvent) {
    std::cout << "handle onSelectSameExtension" << std::flush;
    return false;
}

bool MainWindow::onSortByDate(QKeyEvent *keyEvent) {
    std::cout << "handle onSortByDate" << std::flush;
    return false;
}

bool MainWindow::onSortByExt(QKeyEvent *keyEvent) {
    std::cout << "handle onSortByExt" << std::flush;
    return false;
}

bool MainWindow::onSortByName(QKeyEvent *keyEvent) {
    std::cout << "handle onSortByName" << std::flush;
    return false;
}

bool MainWindow::onSortBySize(QKeyEvent *keyEvent) {
    std::cout << "handle onSortBySize" << std::flush;
    return false;
}

bool MainWindow::onSwapPanels(QKeyEvent *keyEvent) {
    std::cout << "handle onSwapPanels" << std::flush;
    return false;
}

bool MainWindow::onSwitchSide(QKeyEvent *keyEvent) {
    std::cout << "handle onSwitchSide" << std::flush;
    return false;
}

bool MainWindow::onTestArchives(QKeyEvent *keyEvent) {
    std::cout << "handle onTestArchives" << std::flush;
    return false;
}

bool MainWindow::onToggleMarkDown(QKeyEvent *keyEvent) {
    std::cout << "handle onToggleMarkDown" << std::flush;
    return false;
}

bool MainWindow::onToggleMarkTotalSize(QKeyEvent *keyEvent) {
    std::cout << "handle onToggleMarkTotalSize" << std::flush;
    return false;
}

bool MainWindow::onTotalSizes(QKeyEvent *keyEvent) {
    std::cout << "handle onTotalSizes" << std::flush;
    return false;
}

bool MainWindow::onUnselectAllFromNumMinus(QKeyEvent *keyEvent) {
    std::cout << "handle onUnselectAllFromNumMinus" << std::flush;
    return false;
}

bool MainWindow::onUnselectGroup(QKeyEvent *keyEvent) {
    std::cout << "handle onUnselectGroup" << std::flush;
    return false;
}

bool MainWindow::onView(QKeyEvent *keyEvent) {
    std::cout << "handle onView" << std::flush;
    return false;
}

